apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: face-detection
  name: face-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      run: face-detection
  strategy:
    rollingUpdate:
  template:
    metadata:
      labels:
        run: face-detection
    spec:
      hostname: face-detection
      containers:
        - name: face-detection
          image: latonaio/face-detection
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8888"
            - name: VIDEO_PATH
              value: "rtsp://stream-usb-video-by-rtsp-001-srv:8555/usb"
            - name: DETECT_INTERVAL
              value: "0.1"
            - name: TZ
              value: Asia/Tokyo
          ports:
            - containerPort: 8888
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/lib/aion/Data
            - name: ui
              mountPath: /var/lib/aion/FaceDetection/face-detection/public/
          resources:
            limits:
              cpu: "1"
              memory: "200Mi"
            requests:
              cpu: "0.5"
              memory: "100Mi"
      volumes:
      - name: data
        hostPath:
          path: /var/lib/aion/default/Data
      - name: ui
        hostPath:
          path: /var/lib/aion/FaceDetection/face-detection/public/
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: face-detection
  name: face-detection
spec:
  selector:
    run: face-detection
  type: ClusterIP
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
